### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\humhubchat\Events' not found

### ISSUE THREAD

**Issue by MrTorta** [petersmithca/humhub-basic-chat#24]
I removed the module folder as it does not go for the latest version of humhub but now it gives me this error... How can I do?

`
call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\humhubchat\Events' not found`

**Comment by MrTorta** [comment]
I've already solved it myself

**Comment by mandjek** [comment]
@MrTorta,  Good day. How did you manage to solve it please ?

**Comment by lisandi** [comment]
@MrTorta, Good day. How did you manage to solve it please ? It would be nice if yo could short explain how you solved it, or what the problem was so that others can learn out of it too. Thanks!

**Comment by ArchBlood** [comment]
@lisandi first the issue here is that if you're using PHP 7.2+ the extended class needs to be changed to BaseObject to function in newer versions of HumHub that require PHP 7.2 or even 7.3 as in the case of HumHub v1.9.x
https://github.com/petersmithca/humhub-basic-chat/blob/9f56e4c4ef9666497b1d23b026cf3290ed98601a/Events.php#L11

Second, with how the JavaScript used is of now, it's very outdated due to the JavaScript framework changes that have been implemented and later refactored in newer versions to comply with pjax loading, it's recommended to first refactor the scripts to comply with HumHub standards yourself, or ask someone that can to do so

**Comment by lisandi** [comment]
Thanks for the explanations. I thought so already! We use PHP 8.0+ so no wonder. The comment was also meant as a response to "I all ready solved it." and no explanation how it got solved. - Let's bookmark it as Out Dated and not maintained.

**Comment by ArchBlood** [comment]
> Thanks for the explanations. I thought so already! We use PHP 8.0+ so no wonder. The comment was also meant as a response to "I all ready solved it." and no explanation how it got solved. - Let's bookmark it as Out Dated and not maintained.

Should be mentioned in other issues (see: https://github.com/petersmithca/humhub-basic-chat/issues/20#issuecomment-252881689 & https://github.com/petersmithca/humhub-basic-chat/issues/23#issuecomment-373819758)
